### PR TITLE
SoftModem integration

### PR DESCRIPTION
**Pull request by rmeister**
Hi! Nice work!

I'm currently working with this on a [project](https://publiclab.org/notes/rmeister/03-24-2016/browser-based-arduino-sensor-data-transfer-using-webrtc-and-headphone-jack) for Google Summer of Code. Therefore I will add some decoding logic for the [SoftModem](https://github.com/arms22/SoftModem) library, which uses an encoding similar to Bell 202. 

It's not ready to merge, I just wanted to say hello and show there is someone using this cool project :)

Best regards,
Richard

### CODE REVIEW

**Comment by jywarren** [comment]
Hmm, cool, how did you come across Max Ogden's fork? Is it mainly node compatibility or do his changes do more than that?

**Comment by rmeister** [comment]
Just node compatibility. But unfortunately it breaks the web demo.

Thought I can fix this easily with Browserify, but somehow it results in larger changes of the demo scripts. Could not get it to work yet, because the demo scripts depend on each other.

**Comment by jywarren** [comment]
ah, is this where we could use that browserify/node switching trick as I
had mistranscribed into webjack?

**Comment by rmeister** [comment]
Browserify would do that for us, so we could remove it from Webjack. It makes _reqiure('...')_ calls usable in the browser.

What I don't like at this approach is that using Webjack would also require Browserify. But perhaps I misunderstood something?

**Comment by jywarren** [comment]
but browserify then makes (the compiled version of) libraries _unusable_
with commonjs require() -- the idea of the snippet I put in webjack is to
make it available under module.exports -- for use in require()s, but to
skip that if module.exports doesn't exist -- as when it's used in a webpage
directly. That snippet makes it possible to do both with the same file, i
believe -- although it's also possible I misunderstand something!

**Comment by rmeister** [comment]
You are right about Browserify, having two files is not desirable.

Sorry for this seesaw changes, but I think we better drop modem.js. The commits from Max Ogden may make it compatible with node, but they also introduce the dependency of 'audiobuffer'. Also I think my idea to make modem.js compatible with SoftModem was not that great, because  the modem.js demo will end up to be nearly the same as the WebJack demo.
I'd rather take the knowledge from the decoding process, use it to build a decoder solely for SoftModem and close this request.

**Pull request closed without merging**
